module.exports = {
  ROLES: {
    DOCTOR: "doctor",
    NURSE: "nurse",
    INTERN_NURSE: "internNurse",
  },
  GENDER: {
    MALE: "M",
    FEMALE: "F",
    OTHER: "O",
  },
  TESTS: [
    "immunology",
    "autoantibodies",
    "microbiology",
    "blood culture",
    "mantoux test",
    "sputum culture",
    "stool culture",
    "urine culture",
  ],
  MEDICINES: [
    "Acetaminophen",
    "Adderall",
    "Amitriptyline",
    "Amlodipine",
    "Amoxicillin",
    "Ativan",
    "Atorvastatin",
    "Azithromycin",
    "Benzonatate",
    "Brilinta",
    "Bunavail",
    "Buprenorphine",
    "Cephalexin",
    "Ciprofloxacin",
    "Citalopram",
    "Clindamycin",
    "Clonazepam",
    "Cyclobenzaprine",
    "Cymbalta",
    "Doxycycline",
    "Dupixent",
    "Entresto",
    "Entyvio",
    "Farxiga",
    "Fentanyl Patch",
    "Gabapentin",
    "Gilenya",
    "Humira",
    "Hydrochlorothiazide",
    "Hydroxychloroquine",
    "Ibuprofen",
    "Imbruvica",
    "Invokana",
    "Januvia",
    "Jardiance",
    "Kevzara",
    "Leqvio",
    "Lexapro",
    "Lisinopril",
    "Lofexidine",
    "Loratadine",
    "Lyrica",
    "Melatonin",
    "Meloxicam",
    "Metformin",
    "Methadone",
    "Methotrexate",
    "Metoprolol",
    "Mounjaro",
    "Naloxone",
    "Naltrexone",
    "Naproxen",
    "Narcan",
    "Nurtec",
    "Omeprazole",
    "Onpattro",
    "Otezla",
    "Ozempic",
    "Pantoprazole",
    "Plan B",
    "Prednisone",
    "Probuphine",
    "Rybelsus",
    "secukinumab",
    "Sublocade",
    "Tramadol",
    "Trazodone",
    "Viagra",
    "Wegovy",
    "Wellbutrin",
    "Xanax",
    "Zubsolv",
  ],
};
